### ISSUE TITLE
Update / feature request

### ISSUE THREAD

**Issue by simonvh** [Maarten-vd-Sande/qnorm#2]
Currently `quantile_normalize()` does not specify in the docstring if it normalizes row- or column-wise. Maybe an axis parameter would be nice?

**Comment by Maarten-vd-Sande** [comment]
Yes makes sense!

**Comment by Maarten-vd-Sande** [comment]
This is now in the newest release v0.5.0, and should be online on pypi and conda-forge by tomorrow!

qnorm accepts an axis argument, and the README and docstrings should reflect these changes.
